name: nf-core-denovohybrid-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bandage=0.8.1
  - bcftools=1.8
  - fastqc=0.11.8
  - filtlong=0.2.0
  - nanoplot=1.26.2
  - minimap2=2.17
  - multiqc=1.7
  - ngs-bits=2019_04
  - quast=5.0.2
  - r-base=3.5.1
  - r-markdown=0.8
  - porechop=0.2.3_seqan2.1.1
  - seqtk=1.3
  - unicycler=0.4.7
  - wtdbg=2.3
